version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "[dependabot]"
