version: "3.1"

services:

  base:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mne-tools/mne-nirs

  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mne-tools/mne-nirs
    hostname: mne-dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mne-tools/mne-nirs
    hostname: mne-dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]