on: [status]

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-20.04
    name: Run CircleCI artifacts redirector
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    
      - name: Test
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
    
      - name: view the PR number
        run: |
          echo "PR number = ${{ env.PULL_NUMBER }}"
          echo "PR number = $PULL_NUMBER"
          
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/dev/pull/${{ env.PULL_NUMBER }}/index.html
          circleci-jobs: build_docs
