on: [status]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-20.04
    name: Run CircleCI artifacts redirector
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build_docs
