name: 'examples / linux / pip'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 13 * * 1"

jobs:
  job:
    name: 'py3.8'
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    defaults:
      run:
        shell: bash
    env:
      DISPLAY: ':99.0'
      MNE_LOGGING_LEVEL: 'info'
      MNE_STIM_CHANNEL: 'STI101'
      OPENBLAS_NUM_THREADS: '1'
      PYTHONUNBUFFERED: '1'
      PYTHON_VERSION: '3.9'
      MNEPYTHON: 'dev'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./tools/setup_xvfb.sh
        name: 'Setup xvfb'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        name: 'Setup python'
      - name: Download fOLD data
        run: ./tools/fold.sh
      - shell: bash -el {0}
        run: |
          ./tools/github_actions_dependencies.sh
          source tools/get_minimal_commands.sh
        name: 'Install dependencies'
      - shell: bash -el {0}
        run: ./tools/github_actions_install.sh
        name: 'Install MNE'
      - shell: bash -el {0}
        run: ./tools/github_actions_infos.sh
        name: 'Show infos'
      - shell: bash -el {0}
        run: |
          pip list
        name: 'pip list'
      - shell: bash -el {0}
        run: ./tools/github_actions_download.sh
        name: 'Download testing data'
      - shell: bash -el {0}
        run: ./tools/github_actions_locale.sh
        name: 'Print locale'
      - shell: bash -el {0}
        run: ./tools/github_actions_test_examples.sh
        name: 'Run tests'
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
