name: 'tests / macos / conda'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 13 * * 1"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

jobs:
  job:
    name: 'py3.8'
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    defaults:
      run:
        shell: bash
    env:
      PYTHON_VERSION: '3.9'
      MNE_LOGGING_LEVEL: 'warning'
      OPENBLAS_NUM_THREADS: '1'
      PYTHONUNBUFFERED: '1'
      CONDA_ENV: 'environment.yml'
      CI_OS_NAME: 'osx'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'mne-nirs'
          python-version: ${{ env.PYTHON_VERSION }}
          environment-file: ${{ env.CONDA_ENV }}
        name: 'Setup conda'
      - shell: bash -el {0}
        run: |
          ./tools/github_actions_dependencies.sh
          source tools/get_minimal_commands.sh
        name: 'Install dependencies'
      - shell: bash -el {0}
        run: ./tools/github_actions_install.sh
        name: 'Install MNE'
      - shell: bash -el {0}
        run: ./tools/github_actions_infos.sh
        name: 'Show infos'
      - shell: bash -el {0}
        run: ./tools/github_actions_download.sh
        name: 'Download testing data'
      - shell: bash -el {0}
        run: ./tools/github_actions_locale.sh
        name: 'Print locale'
      - shell: bash -el {0}
        run: ./tools/github_actions_test.sh
        name: 'Run tests'
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
