name: "Pull Request Lint Check"

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        use-pylint: false
        use-pycodestyle: true
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
