name: "numpydoc"
on:
- pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true


jobs:
  # PIP + non-default stim channel + log level info
  numpydoc:
    name: 'numpydoc'
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip docs]')"
    defaults:
      run:
        shell: bash
    env:
      DISPLAY: ':99.0'
      MNE_LOGGING_LEVEL: 'info'
      MNE_STIM_CHANNEL: 'STI101'
      OPENBLAS_NUM_THREADS: '1'
      PYTHONUNBUFFERED: '1'
      PYTHON_VERSION: '3.9'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./tools/setup_xvfb.sh
        name: 'Setup xvfb'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        name: 'Setup python'
      - shell: bash -el {0}
        run: |
          ./tools/github_actions_dependencies.sh
          source tools/get_minimal_commands.sh
        name: 'Install dependencies'
      - shell: bash -el {0}
        run: |
          pip install --progress-bar off --upgrade -r requirements_doc.txt
        name: 'Install doc dependencies'
      - shell: bash -el {0}
        run: ./tools/github_actions_install.sh
        name: 'Install MNE'
      - shell: bash -el {0}
        run: ./tools/github_actions_infos.sh
        name: 'Show infos'
      - shell: bash -el {0}
        run: |
          git reset --hard "$GITHUB_SHA"
          git checkout -q -B "$GITHUB_REF"
          git reset --hard "$GITHUB_SHA"
      - shell: bash -el {0}
        run: |
          git status
      - shell: bash -el {0}
        run: ./tools/github_actions_numpydoc.sh
        name: 'Build docs'
